version: "3.8"

services:

  client-a:
    image: gokarni/client-a-node-app:${IMAGE_TAG}
    networks:
      - app-network
    secrets:
      - client_a_db
    configs:
      - source: node_env
        target: /app/.env
    volumes:
      - client_a_data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=app-network"
        - "traefik.http.routers.client-a.rule=Host(`client-a.example.com`)"
        - "traefik.http.services.client-a.loadbalancer.server.port=3000"

  client-b:
    image: gokarni/client-b-python-app:${IMAGE_TAG}
    networks:
      - app-network
    secrets:
      - client_b_db
    volumes:
      - client_b_data:/app/data
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=app-network"
        - "traefik.http.routers.client-b.rule=Host(`client-b.example.com`)"
        - "traefik.http.services.client-b.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v2.10
    networks:
      - app-network
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=app-network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=admin@example.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_cert:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  app-network:
    external: true

secrets:
  client_a_db:
    external: true
  client_b_db:
    external: true

configs:
  node_env:
    external: true

volumes:
  client_a_data:
  client_b_data:
  traefik_cert:
